### ISSUE TITLE
如何解决 arm64 平台运行失败问题？

### ISSUE THREAD

**Issue by yunhouhuang** [coder-free/GDMapSwiftUI#1]
building for 'iOS-simulator', but linking in object file (/Users/hou/AppleProjects/GDMapSwiftUI/MAMapKit.framework/MAMapKit[arm64][2](MAMapKit-arm64-master.o)) built for 'iOS'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by coder-free** [comment]
你这个错误是说，你的 `MAMapKit.framework/MAMapKit` 文件是给 ios 【arm64】编译的，不能在模拟器上运行。一般模拟器可能需要 x86_64，如果你电脑是苹果m系列芯片的电脑，那你得找 针对模拟器编译的的 arm64 的 framework 文件才行。这个你去高德官网应该就能找到。

如果你找到了，可以用 lipo 命令 来合并真机 和模拟器的库文件。
